import Header from "@/components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://blog-moelleer.vercel.app/"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-slate-300 dark:bg-zinc-900 min-h-screen pt-10 lg:pt-20`}
      >
        <Header />
        <main className="pt-10">
          <div className="flex flex-col items-center justify-between">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
